### ISSUE TITLE
Feature Request: Save Character selection too

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [KingEnderBrine/-RoR2-LobbyVotesSave#1]
It would be great if the selected character is also saved.

Also, I am pretty sure my character selection is saved by default in vanilla.

Like for instance, I select Engineer in singleplayer, then exit that menu, enter singleplayer again. Engineer should still be chosen. What happens now is that the selection goes back to Commando.

**Comment by KingEnderBrine** [comment]
> It would be great if the selected character is also saved.

I will think about that.

> Also, I am pretty sure my character selection is saved by default in vanilla.

It restores a character if you died/completed the game and returned to the lobby. If you quit to the main screen and click singleplayer Commando will be selected.

**Comment by KingEnderBrine** [comment]
An update is published, now a selected character is also saved.
