### ISSUE TITLE
lobby config compat

### ISSUE THREAD

**Issue by breadguyyy** [KingEnderBrine/-RoR2-LobbyVotesSave#2]
if possible, could this mod add lobby presets or a toggle to save or not save current settings with your lobby config mod?

**Comment by KingEnderBrine** [comment]
> add lobby presets or a toggle to save or not save current settings

Not sure what you mean by that. Do you want to be able to disable saving individual parts (like character, artifacts, difficulty)? Or disable a whole mod, as `PartialMetamorphosis` or `AccumulativeArtifacts` do? Or both?
